lab_a: lab_a.c
	gcc -o lab_a lab_a.c -std=c99

lab_b: lab_b.c
	gcc -o lab_b lab_b.c -std=c99

lab_c: lab_c.c
	gcc -o lab_c lab_c.c -O0 -std=c99 -g

lab_c1: lab_c.c
	gcc -o lab_c lab_c.c -O1 -std=c99 -g

